# Generated by Django 4.0.4 on 2022-05-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cliente_cpf_alter_cliente_telefone_delete_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, null=True)),
                ('quantidadeDisponivel', models.IntegerField()),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('CPF', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('telefone', models.IntegerField()),
                ('dataNascimento', models.DateField()),
                ('dataAdmissao', models.DateField()),
                ('salarioBruto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dataInicio',
            new_name='dataCadastro',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dataNascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CPFCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
                ('CPFVendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendedor')),
                ('idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produto')),
            ],
        ),
    ]
