# Generated by Django 4.0.4 on 2022-05-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_produto_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='', max_length=300),
        ),
    ]
