# Generated by Django 4.0.5 on 2022-07-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cliente_nome_alter_produto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
